---
abstract: 'A daemonizer'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Daemon-Daemonize
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  IO::Socket::INET: 0
  POSIX: 0
  Path::Class: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/Daemon-Daemonize/tree/master
version: 0.002
